### ISSUE TITLE
XDZIBEC - XO- Missing Portfolio Check in _require Statement

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-unitasprotocol-judging#43]
XDZIBEC

medium

# XO- Missing Portfolio Check in _require Statement

## Summary
- The `_require` statement in the `withdrawCollateral` function of the `InsurancePool` contract is incomplete, as it fails to check the portfolio balance before allowing the `withdrawal`. This omission means that the `_require` statement will always pass, even if the `collateral` is insufficient to cover the `withdrawal` amount.
## Vulnerability Detail
```solidity
/**
     * @notice Withdraws the collateral to the sender
     * @param token Address of the token
     * @param amount Amount of the collateral
     */
    function withdrawCollateral(address token, uint256 amount) external onlyGuardianOrWithdrawer nonReentrant {
        _checkAmountPositive(amount);

        uint256 collateral = _getBalance(token);
        _require(collateral - _getPortfolio(token) >= amount, Errors.POOL_BALANCE_INSUFFICIENT);

        _setBalance(token, collateral - amount);

        IERC20(token).safeTransfer(msg.sender, amount);

        emit CollateralWithdrawn(token, msg.sender, amount);
    }

    /**
```
- the vulnerability is in the  `withdrawCollateral` function, so the problem is that the `_require` statement. The `_require` statement is checking to make sure that the `collateral` is greater than or equal to the `amount` minus the `_getPortfolio`, the `_getPortfolio` function is never called. This means that the `_require` statement will always `pass`, even if the `collateral` is `less` than the `amount`. this  allow users to withdraw more `collateral` than they actually have available, potentially leading to imbalances in the contract's funds and compromising its integrity.
## Impact
- The vulnerability could lead to incorrect withdrawal operations and potential imbalances in the contract.
## Code Snippet
https://github.com/sherlock-audit/2023-04-unitasprotocol/blob/main/Unitas-Protocol/src/InsurancePool.sol#L93C3-L111C8
## Tool used

Manual Review

## Recommendation
- The `_getPortfolio` function should be called before the` _require` statement. This will ensure that the `_require `statement only passes if the `collateral` is actually greater than or equal to the amount minus the `_getPortfolio`.

**Comment by sko94** [comment]
Escalate for 10 USDC
this should be a valid depends on the sherlok rules

**Comment by jacksanford1** [comment]
I don't understand what's going on in this issue description. @sko94 let's start with this:

> the _getPortfolio function is never called

Why does the issue say the _getPortfolio function is never called when it is clearly called in the _require() statement?

**Comment by jacksanford1** [comment]
Result:
Low
Unique

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sko94](https://github.com/sherlock-audit/2023-04-unitasprotocol-judging/issues/43/#issuecomment-1603500302): rejected
