### ISSUE TITLE
0xGoodess - decreaseAllowance has modifier `notBlacklisted(spender)`, which stops other users who would like to revoke allowance to a black-listed address

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-unitasprotocol-judging#53]
0xGoodess

medium

# decreaseAllowance has modifier `notBlacklisted(spender)`, which stops other users who would like to revoke allowance to a black-listed address

## Summary
decreaseAllowance has modifier `notBlacklisted(spender)`, which stops other users who would like to revoke allowance to a black-listed address

## Vulnerability Detail
In ERC20Token implementation, there is a blacklist in wihch addresses are forbidden to be sender/receiver of tokens. It also cannot be recipient nor approver of allowance. However, other users who have previously approved some allowance to this blacklisted address, might want to revoke their allowance now, but cannot do so since decreaseAllowance also have this modifier `notBlacklisted(spender)`. This seems unreasonable/unfair to other users. 

Without the ability to revoke allowance while the black-listed address is in blacklist, in the worst case: the black-listed address could front-run other users `decreaseAllowance` tx as soon as they get removed from the blacklist.

```solidity
    function decreaseAllowance(address spender, uint256 subtractedValue) public whenNotPaused notBlacklisted(msg.sender) notBlacklisted(spender) override returns (bool) {
        address owner = _msgSender();
        uint256 currentAllowance = allowance(owner, spender);
        require(currentAllowance >= subtractedValue, "ERC20: decreased allowance below zero");
        unchecked {
            _approve(owner, spender, currentAllowance - subtractedValue);
        }

        return true;
    }
```
## Impact
other users who would like to revoke allowance to a black-listed address is unable to do so.

## Code Snippet
https://github.com/sherlock-audit/2023-04-unitasprotocol/blob/main/Unitas-Protocol/src/ERC20Token.sol#L241

## Tool used

Manual Review

## Recommendation
Consider to remove `notBlacklisted(spender)` from decreaseAllowance if that's appropriate.

**Comment by chrisckwong821** [comment]
Escalate for 10 USDC
I think this is a legit issue and would kindly ask the sponsor to explain why users are not allowed to reduce allowance for a blacked-list address if otherwise

**Comment by jacksanford1** [comment]
@chrisckwong821 How would this issue result in a material loss of funds for honest users? When answering that question, remember that the root cause of the loss cannot be due to an admin, since admins are trusted. 

If the path to a material loss of funds is not described, this issue should stay invalid.

**Comment by jacksanford1** [comment]
Result:
Low
Unique

**Comment by hrishibhat** [comment]
Result:
Low
Unique

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [chrisckwong821](https://github.com/sherlock-audit/2023-04-unitasprotocol-judging/issues/53/#issuecomment-1605879275): rejected
