### ISSUE TITLE
sashik_eth - Last withdrawal would be blocked

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-unitasprotocol-judging#73]
sashik_eth

medium

# Last withdrawal would be blocked

## Summary

Last withdrawal would be blocked.

## Vulnerability Detail

At the end of the `swap()` execution `Unitas.sol` checks the current reserve ratio and reserve status and reverts swaps in case these values are wrong:
```solidity
File: Unitas.sol
605:     function _checkReserveRatio(uint232 reserveRatioThreshold) internal view {
606:         if (reserveRatioThreshold == 0) {
607:             return;
608:         } else {
609:             (uint256 reserves, uint256 collaterals) = _getTotalReservesAndCollaterals();
610:             uint256 allReserves = reserves + collaterals;
611:             uint256 liabilities = _getTotalLiabilities();
612: 
613:             (ReserveStatus reserveStatus, uint256 reserveRatio) = _getReserveStatus(allReserves, liabilities);
614: 
615:             if (reserveStatus != ReserveStatus.Infinite) { 
616:                 _require(reserveRatio > reserveRatioThreshold, Errors.RESERVE_RATIO_NOT_GREATER_THAN_THRESHOLD);
617:             }
618:         }
619:     }
```

`reserveStatus` could have 3 values:
- `Undefined` when `allReserves` and `liabilities` are zero
- `Infinite` when `liabilities` is zero
- Otherwise `Finite`

So the `_checkReserveRatio()` function would check the `reserveRatio` value in 2 cases - when `allReserves` and `liabilities` are both zero or non-zero.

The second case would take place most time of protocol existence, while the first case could take place when the last token holder would be withdrawing collateral and IP reserves would be equal to 0 (because of protocol become abandoned for example). In such a scenario at the end of the swap execution `allReserves` and `liabilities` would be equal to 0 and the transaction would be reverted due to not enough `reserveRatio` in line 616.

Basically it would create a situation when the contract has enough collateral (1 to 1  to user's tokens) but withdrawing would be impossible.

## Impact

Last withdrawer would not be able to withdraw all left collateral from the protocol.

## Code Snippet

https://github.com/sherlock-audit/2023-04-unitasprotocol/blob/main/Unitas-Protocol/src/Unitas.sol#L615-L617

## Tool used

Manual Review

## Recommendation

Consider updating the reserve ratio check to the next:
```solidity
-           if (reserveStatus != ReserveStatus.Infinite) { 
+           if (reserveStatus == ReserveStatus.Finite) { 
                _require(reserveRatio > reserveRatioThreshold, Errors.RESERVE_RATIO_NOT_GREATER_THAN_THRESHOLD);
            }
```

**Comment by sashik-eth** [comment]
Escalate for 10 USDC
This is a valid medium since the last holder of the usd1 tokens would be unable to withdraw collateral while protocol holds enough (100%) collateral for this.

**Comment by 0xruhum** [comment]
Generally, the issue has to result in a "material amount of funds being lost" to be a valid med/high. https://docs.sherlock.xyz/audits/judging/judging

In this case, the user could just leave 1 wei inside the reserves so that the reserve status is "Infinite". That way they can withdraw 99.9% of their funds.

**Comment by ctf-sec** [comment]
dust amount is left in the contract, valid low

**Comment by jacksanford1** [comment]
@sashik-eth Any response to @0xruhum's method of making sure only a dust amount could be lost from this?

**Comment by sashik-eth** [comment]
@jacksanford1 I agree that sacrificing dust amount would help to save the last withdrawal

**Comment by jacksanford1** [comment]
Result:
Low
Unique

**Comment by hrishibhat** [comment]
Result:
Low
Unique

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sashik-eth](https://github.com/sherlock-audit/2023-04-unitasprotocol-judging/issues/73/#issuecomment-1603137732): rejected
